SEED:
  random_seed: 42

DATALOADER:
  num_workers: 2
  shuffle: False
  pin_memory: True
  drop_last: False

TRAIN:
  num_epochs: 50
  batch_size: 4
  learning_rate: 0.0005
  early_stopping_patience: 20
  model: kykim/bert-kor-base
  optimizer: AdamP
  scheduler:
  momentum:
  weight_decay: 0.00001
  loss_function:
  metric_function:

PERFORMANCE_RECORD:
  column_list:
    - train_serial
    - train_timestamp
    - model_str
    - optimizer_str
    - loss_function_str
    - metric_function_str
    - early_stopping_patience
    - batch_size
    - epoch
    - learning_rate
    - momentum
    - random_seed # -----------key columns-------------
    - epoch_index 
    - train_loss
    - validation_loss
    - train_score
    - validation_score
    - elapsed_time